version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-6"
    config:
      config: .eslintrc.js
      ignore_warnings: true
      extensions:
        - .ts
        - .tsx
        - .js
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 5
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 8
  method-count:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 100
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: false
