version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: 'Setup Environment Variables'
          command: |
            echo 'export CODECOV_TOKEN="$CODECOV_TOKEN"' >> $BASH_ENV
      - run:
          name: 'Install dependencies'
          command: 'yarn install'
      - run:
          name: 'Jest tests and send report to codecov'
          command: 'yarn test:ci && bash <(curl -s https://codecov.io/bash)'

workflows:
  testing:
    jobs:
      - test:
          filters:
              ignore:
                - main
