version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: 'Setup Environment Variables'
          command: |
            echo 'export CODECOV_TOKEN="$CODECOV_TOKEN"' >> $BASH_ENV
            echo 'export CC_TEST_REPORTER_ID="$CC_TEST_REPORTER_ID"' >> $BASH_ENV
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: 'Install dependencies'
          command: 'yarn install'
      - run:
          name: 'Run tests and get coverage'
          command: 'yarn test:ci'
      - run:
          name: 'Send test coverage to CodeCov'
          command: |
            bash <(curl -s https://codecov.io/bash)
            ./cc-test-reporter after-build -t lcov -p ./coverage/lcov.info

workflows:
  testing:
    jobs:
      - test:
          filters:
            branches:
              ignore: main
